name: Build & Push Docker Images

on:
  push:
    tags:
      - 'v*' # Chạy khi có tag mới

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Cấp quyền ghi vào GHCR
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      # 1. Đăng nhập vào Github Container Registry
      # Sử dụng luôn Token có sẵn, không cần setup mật khẩu gì cả
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 2. Build & Push GATEWAY
      - name: Build and Push Gateway
        run: |
          # Chuyển tên owner về chữ thường (TranDung6129 -> trandung6129)
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          
          IMAGE_NAME=ghcr.io/$OWNER_LC/landslide-gateway
          TAG=${{ steps.get_version.outputs.VERSION }}
          
          cd gateway 
          
          # Build
          docker build -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest .
          
          # Push
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest

      # 3. Build & Push SERVER 
      - name: Build and Push Server
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          
          IMAGE_NAME=ghcr.io/$OWNER_LC/landslide-server
          TAG=${{ steps.get_version.outputs.VERSION }}
          
          cd server
          docker build -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest